### ISSUE TITLE
ungoogled-chromium-ozone 79.0.3945.79-1 not launching

### ISSUE THREAD

**Issue by GraveDigger1** [jstkdng/ungoogled-chromium-archlinux#10]
i just installed ungoogled-chromium-ozone 79.3945.79-1 on manjaro kde 18.1.5 testing build via manjaro's update / software manager. from what i can see it looks like it installed without issue, but when i try to launch ungoogled-chromium it does nothing. i do not even get a error message to post. i;ve done a logoff and a reboot and neither fixed the issue. suggestions on how to fix this would be greatly appreciated. thanks

**Comment by jstkdng** [comment]
Do you get any messages in the terminal when trying to start it?

**Comment by GraveDigger1** [comment]
i get the following.

`(chromium:8811): Gtk-WARNING **: 11:45:38.465: cannot open display: :0`

**Comment by jstkdng** [comment]
Just added some patches, once it is done, download the package from here: https://build.opensuse.org/package/show/home:justkidding:arch/ungoogled-chromium-ozone
It should help you avoid recompiling again.

**Comment by GraveDigger1** [comment]
ok i see 2 from 2 hours ago you did. those the ones you mean? if so how do i use the .patch files? also i just realized i need to register to download from there, i'm not registering on a site i might never use again.

**Comment by jstkdng** [comment]
Download the package from this link: https://download.opensuse.org/repositories/home:/justkidding:/arch/standard/x86_64/ungoogled-chromium-79.0.3945.130-1-x86_64.pkg.tar.xz
I'll upload those patches to the aur if it fixes the issues.

**Comment by jstkdng** [comment]
no wait, I fucked up, forgot to enable ozone in the flags. You'll have to wait for it to compile again. Once it is done you should be able to download it from https://download.opensuse.org/repositories/home:/justkidding:/arch/standard/x86_64/
sorry for that

**Comment by GraveDigger1** [comment]
```
conflicting dependencies:
ungoogled-chromium and ungoogled-chromium-ozone are in conflict
```
```
Preparing...
Resolving dependencies...
Checking inter-conflicts...
Failed to prepare transaction:
conflicting dependencies:
ungoogled-chromium and ungoogled-chromium-ozone are in conflict
```

**Comment by jstkdng** [comment]
Yes, you have to replace it.

**Comment by GraveDigger1** [comment]
ok didn't realize i need a ozone patch. updating now, will report back results.

**Comment by GraveDigger1** [comment]
o.k. updated, icon clicked and still won't launch. did reboot tried again and same thing.

**Comment by jstkdng** [comment]
yeah, I got the same error. Are you running under wayland? Because that is the reason of the ozone patches. 
Try running chromium this way:
```
$ chromium --ozone-platform=x11
```
That should be able to open if you are under X11. It also doesn't work with the nvidia driver at all, so if you have nvidia and or running X11 just use https://aur.archlinux.org/packages/ungoogled-chromium/
I have a repository set up if you don't want to compile ungoogled chromium: https://github.com/jstkdng/ungoogled-chromium-archlinux#downloads

**Comment by GraveDigger1** [comment]
i'm not even sure what wayland is. as for the second half of your post that should resolve the issue, cause yes i'm running the nvidia drivers. will uninstall ozone version and install the other and report back.

**Comment by jstkdng** [comment]
If you don't know what wayland is why did you download it lmao. Oh well, it shouldn't have any problem.

**Comment by GraveDigger1** [comment]
first i did not download it. either you installer did or it came with manjaro or something else needed it and installed it. now i finally go the new file installed and ungoogled-chromium is installed and working. thank ever so much for all the help, it is greatly appreciated.
