### ISSUE TITLE
VAAPI is broken

### ISSUE THREAD

**Issue by alium** [jstkdng/ungoogled-chromium-archlinux#11]
as mentioned (https://github.com/ungoogled-software/ungoogled-chromium-archlinux/issues/48#issuecomment-586718742) for me (Ryzen 5 3400G) is in ungoogled-chromium 80.0.x.x broken VAAPI .
i tested mesa-git, now i installed mesa-19.3.4-2, but same problem

**Comment by alium** [comment]
mesa 19.3.3 = video playback is broken

**Comment by jstkdng** [comment]
what kernel are you using? does that happen to only that stream, or to others as well?

**Comment by alium** [comment]
i use kernel linux-zen 5.5.4

video playback is broken on live stream (ivysilani.cz, o2.tv), youtube seems ok, vimeo.com has some broken videos (no live stream) for example: https://vimeo.com/140983024, another videos are ok

**Comment by alium** [comment]
ok, so i found that problem....

VAAPI is not broken. this broking makes enabled rasterization. If i switch to software only, video play clearly again.

btw. i tested all on my old laptop with Intel Haswell and Archlinux too, so no bug via upgrade system or chromium.

**Comment by alium** [comment]
the previous comment was somewhat premature. :-(

on my Intel Haswell laptop, there is no error - neither ver 79 nor ver 80.0.x.x . 
system is up-to-data (same versions as my desktop with Ryzen)

**Comment by jstkdng** [comment]
AMD drivers have always being unstable and if intel works as expected then there's really nothing I can do.

**Comment by alium** [comment]
yes, but we know now, it's no problem of chromium. thank you for your time!

**Comment by alium** [comment]
btw... thank you a very much for your works, i use your works for ungoogled-chromium build in artixlinux

**Comment by jstkdng** [comment]
no problem m8, glad to know my work is useful to others.
