### ISSUE TITLE
pkgname

### ISSUE THREAD

**Issue by kovetskiy** [jstkdng/ungoogled-chromium-archlinux#12]
Hi,

first of all, thank you for packaging and providing `jk-aur` repository, it is really a time saver.

I wanted to add the `github.com/jstkdng/ungoogled-chromium-archlinux` into my own service called aurora which automatically clones AUR (or not aur) pkgbuild repositories and runs makepkg against them (in containers) and then distributes it as an arch repository.  Here it is: https://github.com/kovetskiy/aurora

Could you rename your package into ungoogled-chromium-bin as it was in AUR (before the package deletion) so it will not conflict with existing AUR ungoogled-chromium package?

**Comment by jstkdng** [comment]
why not just use this repository instead of the aur one? :)

**Comment by jstkdng** [comment]
no response from OP for 2 months, closing.
