### ISSUE TITLE
New patch added to chromium official repository

### ISSUE THREAD

**Issue by ghost** [jstkdng/ungoogled-chromium-archlinux#13]
I just want to tell you that there is a new patch added to chromium official build for Archlinux

https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/chromium&id=b09cf910e816b3bdf0788197e9f50e5f29f58fc8

**Comment by jstkdng** [comment]
seems that patch isnt anything mission critical, will add it later

**Comment by jstkdng** [comment]
just added the patch, it is building rn.

**Comment by ghost** [comment]
Because I build your repositry I just want to make sure that everything is okay before buildings it
