### ISSUE TITLE
rebuild with new re2

### ISSUE THREAD

**Issue by quite** [jstkdng/ungoogled-chromium-archlinux#14]
Is the binary in the jk repo build from here? It needs rebuilding with new re2 lib

**Comment by ghost** [comment]
OBS dependacies for archlinux are updated periodically not daily.

I know it sucks how every `re2` update breaks chromium and I started to think that this library needs to be statically linked. is it possible @jstkdng ?

**Comment by jstkdng** [comment]
Thanks for reminding me @quite , will update my repository asap.

@Rowisi
It can be done, but I want to stick to arch's pkgbuild as close as possible.

**Comment by ghost** [comment]
This particular change won't make any problem and will solve this huge problem of breaking all chromium derived packages from AUR.

re2 has only 1 dependacy and it is gcc-libs. static linking will keep chromium running forever and without worrying about updates.

at the end its all up to you if you want to do it or not.

**Comment by jstkdng** [comment]
I don't mind doing it if upstream does the same. Though, that is a separate issue unrelated to what @quite asked originally. If you want to continue discusing this, open a new issue.

**Comment by ghost** [comment]
Its not an issue. just a workaround that I did it already so it doesn't matters.

**Comment by jstkdng** [comment]
oh well, you do you
