### ISSUE TITLE
rebuild with idle-inhibit-v1 protocol

### ISSUE THREAD

**Issue by steven-gg** [jstkdng/ungoogled-chromium-archlinux#15]
If possible, please compile ungoogled-chromium-ozone with idle-inhibit-v1 enabled. Wlroots-based Wayland compositors  such as sway and wayfire use it. Kwin Wayland compositor also supports the protocol.

**Comment by jstkdng** [comment]
how is that achieved, with a build flag?

**Comment by jstkdng** [comment]
No answer from OP for some time now. Closing.
