### ISSUE TITLE
error: failed to commit transaction (invalid or corrupted package (checksum))

### ISSUE THREAD

**Issue by gothmog123** [jstkdng/ungoogled-chromium-archlinux#16]
Hi I get the following message when isntalling from the repo with pacman:

:: File /var/cache/pacman/pkg/ungoogled-chromium-83.0.4103.116-2-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (checksum)).
Do you want to delete it? [Y/n] y
error: failed to commit transaction (invalid or corrupted package (checksum))
Errors occurred, no packages were upgraded.

**Comment by jstkdng** [comment]
hello, thanks for telling me. Fixed.
