### ISSUE TITLE
VAAPI error not working  since 83.0.4103.116-2

### ISSUE THREAD

**Issue by bkmo** [jstkdng/ungoogled-chromium-archlinux#17]
On intel i915 skylake manjaro/arch I no longer have HW accelerated video with ungoogled. Works on version 83.0.4103-116-1.
Log throws up an error VAAPI.

**Comment by jstkdng** [comment]
Please give more info about your cpu.

**Comment by bkmo** [comment]
Intel Skylake GT2 [HD Graphics 520]  

VENDOR= 0x8086 [Intel], DEVICE=0x1916 [Mesa Intel(R) HD Graphics 520 (SKL GT2)] *ACTIVE*
--
I am going to install the 116-2 build now to get the exact log output.

**Comment by bkmo** [comment]
[16403:16403:0704/145640.121065:ERROR:vaapi_wrapper.cc(503)] : The system version 1.7 should be greater than or equal to 1.8

This error is not in the 116-1 package.   I have tried other binary packages other than yours and they are all broken.

**Comment by jstkdng** [comment]
just updated the patch, can you test? https://download.opensuse.org/repositories/home:/justkidding:/arch/standard/x86_64/ungoogled-chromium-83.0.4103.116-2-x86_64.pkg.tar.zst

**Comment by bkmo** [comment]
I am trying to download it but it is extremely slow. 256k download on a
30meg connection.

**Comment by jstkdng** [comment]
well, can't really do anything about that, that's on the opensuse's servers.

**Comment by bkmo** [comment]
I see that....oh well...still have an hour to go.

**Comment by jstkdng** [comment]
If it's too slow you can get it from here: https://repo.vin.ovh/arch/x86_64/test/ungoogled-chromium-83.0.4103.116-2-x86_64.pkg.tar.zst

**Comment by bkmo** [comment]
That's better, downloading a 25meg, got it

**Comment by bkmo** [comment]
Same error:

   - [224517:224517:0704/211859.091791:ERROR:vaapi_wrapper.cc(503)] : The
   system version 1.7 should be greater than or equal to 1.8



Still
kVideoDecoderName
"FFmpegVideoDecoder"

**Comment by jstkdng** [comment]
what is your output of `vainfo` ? Maybe your system is out of date.

**Comment by bkmo** [comment]
Fully up to date Manjaro.
vainfo: VA-API version: 1.7 (libva 2.7.1)

**Comment by jstkdng** [comment]
Just that? weird
do you have `intel-media-driver` or `libva-intel-driver` installed?

**Comment by bkmo** [comment]
Looking at intel git there was a libva 2.8 released a week ago. Obviously
this has not made it to the Manjaro repositories yet. I am going to look at
Arch repos and see if it fixes it.

**Comment by bkmo** [comment]
I had libva-intel, but tried intel-media when it did not work. Going back
to an earlier build of ungoogled works fine.

**Comment by jstkdng** [comment]
Libva is also on 2.7.1 under Arch
maybe your libva provider is out-dated?
for eg, my `vainfo` output
```
vainfo: VA-API version: 1.8 (libva 2.7.1)
vainfo: Driver version: Mesa Gallium driver 20.1.2 for Radeon RX 570 Series (POLARIS10, DRM 3.37.0, 5.7.7-1-ck-zen, LLVM 10.0.0)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
```

**Comment by bkmo** [comment]
Libva 2.8 is in Manjaro testing.....gonna grab it now.

**Comment by bkmo** [comment]
Downloading and installing libva-2.8.0-1-x86_64  from Arch repositories
give me:
vainfo: VA-API version: 1.8 (libva 2.7.1)
and also "MojoVideoDecoder"

**Comment by bkmo** [comment]
Manjaro has not released a stable update in 3 weeks.
