### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by r3v1** [jstkdng/ungoogled-chromium-archlinux#2]
I was building with `makepkg -i PKGBUILD` and everything was correct:

> [david@msi]: ungoogled-chromium-archlinux>$ makepkg -i PKGBUILD 
> ==> Creando el paquete: ungoogled-chromium 76.0.3809.100-2 (dom 11 ago 2019 22:06:01 CEST)
> ==> Comprobando dependencias mientras se ejecuta...
> ==> Comprobando dependencias mientras se compila...
> ==> Recibiendo las fuentes...
>   -> chromium-76.0.3809.100.tar.xz ha sido encontrado 
>   -> chromium-launcher-6.tar.gz ha sido encontrado 
>   -> ungoogled-chromium-76.0.3809.100-1.tar.gz ha sido encontrado 
>   -> ungoogled-chromium-archlinux-master.tar.gz ha sido encontrado 
>   -> chromium-drirc-disable-10bpc-color-configs.conf ha sido encontrado 
> ==> Validando los archivos source con sha256sums...
>     chromium-76.0.3809.100.tar.xz ... Aprobado
>     chromium-launcher-6.tar.gz ... Aprobado
>     ungoogled-chromium-76.0.3809.100-1.tar.gz ... Omitido
>     ungoogled-chromium-archlinux-master.tar.gz ... Omitido
>     chromium-drirc-disable-10bpc-color-configs.conf ... Aprobado
> ==> Extrayendo las fuentes...
>   -> Extrayendo chromium-76.0.3809.100.tar.xz con bsdtar
>   -> Extrayendo chromium-launcher-6.tar.gz con bsdtar
>   -> Extrayendo ungoogled-chromium-76.0.3809.100-1.tar.gz con bsdtar
>   -> Extrayendo ungoogled-chromium-archlinux-master.tar.gz con bsdtar
> ==> Iniciando prepare()...
>   -> Pruning binaries
>   -> Applying patches
> INFO: Applying patches from /home/david/Git/ungoogled-chromium-archlinux/src/ungoogled-chromium-76.0.3809.100-1/patches
> INFO: * Applying chromium-exclude_unwind_tables.patch (1/88)
> DEBUG: /usr/bin/patch -p1 --ignore-whitespace -i /home/david/Git/ungoogled-chromium-archlinux/src/ungoogled-chromium-76.0.3809.100-1/patches/core/inox-patchset/chromium-exclude_unwind_tables.patch -d . --no-backup-if-mismatch --forward
> patching file build/config/compiler/compiler.gni
> INFO: * Applying 0001-fix-building-without-safebrowsing.patch (2/88)
> ...

But an error raised when patching file `url/url_util.cc` like it says:

> INFO: * Applying block-trk-and-subdomains.patch (27/88)
> DEBUG: /usr/bin/patch -p1 --ignore-whitespace -i /home/david/Git/ungoogled-chromium-archlinux/src/ungoogled-chromium-76.0.3809.100-1/patches/core/ungoogled-chromium/block-trk-and-subdomains.patch -d . --no-backup-if-mismatch --forward
> patching file chrome/browser/autocomplete/chrome_autocomplete_scheme_classifier.cc
> patching file chrome/browser/history/history_utils.cc
> patching file chrome/browser/ui/singleton_tabs.cc
> patching file components/omnibox/browser/autocomplete_input.cc
> patching file content/browser/child_process_security_policy_impl.cc
> patching file net/url_request/url_request.cc
> patching file url/url_constants.cc
> patching file url/url_constants.h
> patching file components/url_formatter/url_fixer.cc
> patching file net/BUILD.gn
> patching file android_webview/browser/net/aw_url_request_context_getter.cc
> patching file chrome/browser/profiles/profile_io_data.cc
> patching file chromecast/browser/url_request_context_factory.cc
> The next patch would create the file net/url_request/trk_protocol_handler.cc,
> which already exists!  Skipping patch.
> 1 out of 1 hunk ignored
> The next patch would create the file net/url_request/trk_protocol_handler.h,
> which already exists!  Skipping patch.
> 1 out of 1 hunk ignored
> patching file net/url_request/url_request_context_builder.cc
> patching file url/url_util.cc
> Traceback (most recent call last):
>   File "/home/david/Git/ungoogled-chromium-archlinux/src/ungoogled-chromium-76.0.3809.100-1/utils/patches.py", line 159, in <module>
>     main()
>   File "/home/david/Git/ungoogled-chromium-archlinux/src/ungoogled-chromium-76.0.3809.100-1/utils/patches.py", line 155, in main
>     args.callback(args)
>   File "/home/david/Git/ungoogled-chromium-archlinux/src/ungoogled-chromium-76.0.3809.100-1/utils/patches.py", line 113, in _apply_callback
>     patch_bin_path=args.patch_bin)
>   File "/home/david/Git/ungoogled-chromium-archlinux/src/ungoogled-chromium-76.0.3809.100-1/utils/patches.py", line 54, in apply_patches
>     subprocess.run(cmd, check=True)
>   File "/usr/lib/python3.7/subprocess.py", line 487, in run
>     output=stdout, stderr=stderr)
> **subprocess.CalledProcessError: Command '['/usr/bin/patch', '-p1', '--ignore-whitespace', '-i', '/home/david/Git/ungoogled-chromium-archlinux/src/ungoogled-chromium-76.0.3809.100-1/patches/core/ungoogled-chromium/block-trk-and-subdomains.patch', '-d', '.', '--no-backup-if-mismatch', '--forward']' returned non-zero exit status 1.**
> ==> ERROR: Se produjo un fallo en prepare().
>     Cancelando...

Running on `Linux msi 5.2.8-arch1-1-ARCH #1 SMP PREEMPT Fri Aug 9 21:36:07 UTC 2019 x86_64 GNU/Linux`

**Comment by ghost** [comment]
thing is, you have to clean/remove the build dir completely , else you get those errors like
```
The next patch would create the file net/url_request/trk_protocol_handler.cc,
which already exists! Skipping patch.
1 out of 1 hunk ignored
```

by build dir I mean `BUILDDIR=` in `/etc/makepkg.conf`
but actually removing `$srcdir` or `$srcdir/chromium-${_chromium_version}` is enough (`$srcdir` as seen from `PKGBUILD`)

Alternatively, once you made sure `prepare()` ran successfully once(you can't run it more than once without cleaning the above dir), subsequent (re)compilations could be done by passing `--noprepare --noextract` to `makepkg`

**Comment by jstkdng** [comment]
You could also use ```makepkg -e``` to use the existing $srcdir.
Also, kinda weird github didn't notify me of this issue lmao.

**Comment by jstkdng** [comment]
no response from OP for some time now so closing.
