### ISSUE TITLE
Why is it asking Jre, it differs to Chrome?

### ISSUE THREAD

**Issue by abdulbadii** [jstkdng/ungoogled-chromium-archlinux#20]
Why is it asking Jre, so it's not a pure cpu binary like Chrome is?

**Comment by jstkdng** [comment]
Chromium is comprised of many source files in many languages that are compiled and then added to a single binary. The jre is only a build dependency.

**Comment by abdulbadii** [comment]
I meant compares to 'real' Google Chrome end-result, e.g. its Windows executable, it has nothing with java at end-user run time.
So is this possible to require it at build time but still has such Chrome characteristic above, ie. end-result is native to certain cpu binary into which it's meant, built and distributed?

**Comment by jstkdng** [comment]
well, I'm not familiar with every source file from chromium as it is huge project. The most probable reason is that java is used to build a tool (written in java) that helps with the processing of certain files during compilation. Since it is a build-time tool, it is not added to final binary.

**Comment by abdulbadii** [comment]
I'm cross-checking and investigating the official Chromium build homepage. Thanks much !

**Comment by abdulbadii** [comment]
As I guess the conventional way of build is without JRE.
So what the advantage including JRE as part of build, is it faster, more efficient, by how many percents?
