### ISSUE TITLE
error: failed retrieving file 'jk-aur.db' from repo.vin.ovh : The requested URL returned error: 404

### ISSUE THREAD

**Issue by quite** [jstkdng/ungoogled-chromium-archlinux#21]

**Comment by jstkdng** [comment]
yeah, I've been migrating to a new vps. Some downtime is expected.

**Comment by jstkdng** [comment]
Alright, just finished migrating the repository. Closing.
![image](https://user-images.githubusercontent.com/52050345/91558746-7f197980-e8fc-11ea-85a6-0e792491ea83.png)
