### ISSUE TITLE
What happened to ungoogled-chromium-ozone?

### ISSUE THREAD

**Issue by quantizzed** [jstkdng/ungoogled-chromium-archlinux#22]
Hi!

I noticed that the `ungoogled-chromium-ozone` package has disappeared from the AUR. I wonder, why? Did I miss something?

**Comment by jstkdng** [comment]
Latest ungoogled-chromium package has ozone support built in, thus ungoogled-chromium-ozone is no longer needed.

**Comment by quantizzed** [comment]
Ah, thanks, I didn't know.
