### ISSUE TITLE
PKGBUILD URLS to chromium_version.txt and revision.txt not working

### ISSUE THREAD

**Issue by hchr** [jstkdng/ungoogled-chromium-archlinux#7]
curl -sL https://raw.githubusercontent.com/Eloston/ungoogled-chromium/${_ungoogled_version}/chromium_version.txt
404: Not Found

curl -sL https://raw.githubusercontent.com/Eloston/ungoogled-chromium/${_ungoogled_version}/revision.txt
404: Not Found

When adding /master/ after ungoogled-chromium/
it works.

curl -sL https://raw.githubusercontent.com/Eloston/ungoogled-chromium/master/${_ungoogled_version}/chromium_version.txt
78.0.3904.108

curl -sL https://raw.githubusercontent.com/Eloston/ungoogled-chromium/master/${_ungoogled_version}/revision.txt
1

**Comment by jstkdng** [comment]
hmm, weird, you should probably take the issue to upstream, https://github.com/ungoogled-software/ungoogled-chromium-archlinux

**Comment by hchr** [comment]
Done. Thank you. 
https://github.com/ungoogled-software/ungoogled-chromium-archlinux/issues/43
