### ISSUE TITLE
Latest Update Fails Due To Some Mismach

### ISSUE THREAD

**Issue by neurodiverseEsoteric** [jstkdng/ungoogled-chromium-archlinux#8]
Building ungoogled-chromium-bin... ==> Making package: ungoogled-chromium-bin 79.0.3945.79-2 (Sat 14 Dec 2019 10:58:53 AM PST) ==> Checking runtime dependencies... ==> Checking buildtime dependencies... ==> Retrieving sources... -> Found ungoogled-chromium-79.0.3945.79-1-x86_64.pkg.tar.xz ==> Validating source files with sha256sums... ungoogled-chromium-79.0.3945.79-1-x86_64.pkg.tar.xz ... FAILED ==> ERROR: One or more files did not pass the validity check!

**Comment by jstkdng** [comment]
I suppose you are using and aur helper.
Try deleting the ungoogled-chromium-79.0.3945.79-1-x86_64.pkg.tar.xz file and download it again.

**Comment by neurodiverseEsoteric** [comment]
I tried that now the file can't be downloaded
